Removed rtps example that breaks because of eprosima change
src/rtps.cc:48:32: error: ‘class eprosima::fastrtps::rtps::BuiltinAttributes’ has no member named ‘leaseDuration’
   participant_att.rtps.builtin.leaseDuration = c_TimeInfinite;